import React from 'react';
import { Text, View } from 'react-native';
import { ScrollView } from 'react-native';

export default function Tab3Screen() {
  return (
    <ScrollView>
      <Text>스크린3</Text>
      <Text>스크린3</Text>
      <Text>스크린3</Text>
      <Text>스크린3</Text>
      <Text>스크린3</Text>
      <Text>스크린3</Text>
      <Text>스크린3</Text>
      <Text>스크린3</Text>
      <Text>스크린3</Text>
      <Text>스크린3</Text>
      <Text>스크린3</Text>
      <Text>스크린3</Text>
      <Text>스크린3</Text>
      <Text>스크린3</Text>
      <Text>스크린3</Text>
      <Text>스크린3</Text>
      <Text>스크린3</Text>
      <Text>스크린3</Text>
      <Text>스크린3</Text>
      <Text>스크린3</Text>
      <Text>스크린3</Text>
      <Text>스크린3</Text>
      <Text>스크린3</Text>
      <Text>스크린3</Text>
      <Text>스크린3</Text>
      <Text>스크린3</Text>
      <Text>스크린3</Text>
      <Text>스크린3</Text>
      <Text>스크린3</Text>
      <Text>스크린3</Text>
      <Text>스크린3</Text>
      <Text>스크린3</Text>
      <Text>스크린3</Text>
      <Text>스크린3</Text>
      <Text>스크린3</Text>
      <Text>스크린3</Text>
      <Text>스크린3</Text>
      <Text>스크린3</Text>
      <Text>스크린3</Text>
      <Text>스크린3</Text>
      <Text>스크린3</Text>
      <Text>스크린3</Text>
      <Text>스크린3</Text>
      <Text>스크린3</Text>
      <Text>스크린3</Text>
      <Text>스크린3</Text>
      <Text>스크린3</Text>
      <Text>스크린3</Text>
      <Text>스크린3</Text>
      <Text>스크린3</Text>
      <Text>스크린3</Text>
      <Text>스크린3</Text>
      <Text>스크린3</Text>
      <Text>스크린3</Text>
      <Text>스크린3</Text>
      <Text>스크린3</Text>
      <Text>스크린3</Text>
      <Text>스크린3</Text>
      <Text>스크린3</Text>
      <Text>스크린3</Text>
      <Text>스크린3</Text>
      <Text>스크린3</Text>
      <Text>스크린3</Text>
      <Text>스크린3</Text>
      <Text>스크린3</Text>
      <Text>스크린3</Text>
      <Text>스크린3</Text>
      <Text>스크린3</Text>
      <Text>스크린3</Text>
      <Text>스크린3</Text>
      <Text>스크린3</Text>
      <Text>스크린3</Text>
      <Text>스크린3</Text>
      <Text>스크린3</Text>
      <Text>스크린3</Text>
      <Text>스크린3</Text>
      <Text>스크린3</Text>
      <Text>스크린3</Text>
      <Text>스크린3</Text>
      <Text>스크린3</Text>
      <Text>스크린3</Text>
      <Text>스크린3</Text>
      <Text>스크린3</Text>
      <Text>스크린3</Text>
      <Text>스크린3</Text>
      <Text>스크린3</Text>
      <Text>스크린3</Text>
      <Text>스크린3</Text>
      <Text>스크린3</Text>
      <Text>스크린3</Text>
      <Text>스크린3</Text>
      <Text>스크린3</Text>
      <Text>스크린3</Text>
      <Text>스크린3</Text>
      <Text>스크린3</Text>
      <Text>스크린3</Text>
      <Text>스크린3</Text>
      <Text>스크린3</Text>
      <Text>스크린3</Text>
      <Text>스크린3</Text>
      <Text>스크린3</Text>
      <Text>스크린3</Text>
      <Text>스크린3</Text>
      <Text>스크린3</Text>
    </ScrollView>
  );
}